### ISSUE TITLE
Nefunkční nekos-lewd neko

### ISSUE THREAD

**Issue by ViktorianoCZ** [danbulant/ssps-bot#1]
Zdravím,

V kódu je chyba, která způsobuje nefunkčnost jednoho ze stěžejních příkazů bota, chybu se mi podařilo identifikovat a prosím o rychlé opravení. V souboru nekos-lewd.js je potřeba upravit řádek 6 na "module.exports = class NekosCommand extends commando.Command {" předem děkuji za opravu

**Comment by danbulant** [comment]
Není bug je to feature

**Comment by ViktorianoCZ** [comment]
Nesouhlasím, je to zásadní funkce bota, jak by její odstranění mohlo být feature?
